### ISSUE TITLE
Assumes people are on mastodon.social

### ISSUE THREAD

**Issue by jaranta** [rknightuk/mastodon-toot-bookmarklet#1]
I have no account on mastodon.social, so trying to share anything with this bookmarklet just takes me to the sign in page.

Preferably this would use whatever instance is set to handle mastodon links in the browser (like this share button: https://jonne.arjoranta.fi/2018/indiewebify/)

**Comment by rknightuk** [comment]
> Assumes people are on mastodon.social

I default to mastodon.social because it's the de facto instance and I wasn't aware you could set links to do that.

`web+mastodon://share?text={URL}`

Have you got any information about how to set handlers to handle the `web-mastodon` links? I can't work out how to do it (in Chrome, but any info for any browser would be useful).

I'm happy to add an option to do this, but it won't be the default.

**Comment by jaranta** [comment]
Mastodon.social isn't the biggest instance and there are over a million users on other instances so it might make sense to think about supporting other instances.

It at least used to be that when you created a new account on a instance it would suggest to your browser to become the handler for those links. Firefox is the default handler for all my instances. I'm not sure what the technical implementation is. You should probably look at the Mastodon repo and ask there? Sorry I can't be of more help.

**Comment by rknightuk** [comment]
I didn't say it was the biggest.

> think about supporting other instances.

It does support other instances, you just need to type in your instance. I'll be honest this isn't something I'm concerned about and won't be putting any more time into trying to support.

If anyone sees this issue and has more info, I'll happily look into it but as I said above, it won't be the default behaviour.

**Comment by sophware** [comment]
@jaranta 

I like the implementation in the bookmarklet in this repository.

The share button at https://jonne.arjoranta.fi/2018/indiewebify/ doesn't work for me. If it did, would it cause issues for me, given that I am usually logged in to at least two instances at once? 

For the bookmarklet approach here, I've created two and they work great (posting to the instance I intend).

**Comment by rknightuk** [comment]
Closing, very old issue.
